---
- hosts: leaf1-DC1, leaf2-DC1
  gather_facts: no
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/mlag_vars.yml"
      name: mlag
  - name: Create template
    template:
      src: "{{lookup('env','PWD')}}/templates/mlag.j2"
      dest: "{{lookup('env','PWD')}}/configs/mlag-{{ inventory_hostname }}.cfg"
  - name: Upload config
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/mlag-{{ inventory_hostname }}.cfg"
